# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GETube' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
		pod 'GoogleAPIClient/Drive'
		pod 'GoogleAPIClient/YouTube’
	       pod "youtube-ios-player-helper", "~> 0.1.6”
	      pod 'NSDate+TimeAgo'
		pod 'DGActivityIndicatorView'
	pod 'MMDrawerController', '~> 0.5.7'
  # Pods for GETube

  target 'GETubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GETubeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
